name: Lint diagnostics
on:
  pull_request:
  push:
    branches:
      - rolling

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }} on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        linter: [
            cppcheck,
            cpplint,
            flake8,
            # pep257,
            uncrustify,
            xmllint,
          ]
        include:
          - distro: foxy
            os: ubuntu-20.04
          - distro: humble
            os: ubuntu-22.04
          - distro: rolling
            os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: ${{ matrix.distro }}
          linter: ${{ matrix.linter }}
          package-name: diagnostic_aggregator
            diagnostic_updater
            self_test
